"""
Auto-generate Hugging Face model cards for Molfun models.

Produces a README.md in the HF model card format with metadata
(architecture, training strategy, metrics) and usage examples.
"""

from __future__ import annotations
from typing import Optional
from datetime import datetime


def generate_model_card(
    model_summary: dict,
    metrics: Optional[dict] = None,
    dataset_name: Optional[str] = None,
    objective: Optional[str] = None,
    tags: Optional[list[str]] = None,
) -> str:
    """
    Generate a Hugging Face model card markdown string.

    Args:
        model_summary: Output of ``MolfunStructureModel.summary()``.
        metrics: Optional evaluation metrics dict.
        dataset_name: Name of the training dataset.
        objective: Training objective description.
        tags: Extra tags for the model card.

    Returns:
        Model card as a markdown string with YAML front matter.
    """
    all_tags = ["molfun", "protein-structure", "molecular-ml"]
    if tags:
        all_tags.extend(tags)
    strategy = model_summary.get("strategy", {})
    if isinstance(strategy, dict) and strategy.get("name"):
        all_tags.append(strategy["name"])

    yaml_lines = [
        "---",
        "library_name: molfun",
        "license: apache-2.0",
        f"tags: [{', '.join(all_tags)}]",
    ]
    if dataset_name:
        yaml_lines.append(f"datasets: [{dataset_name}]")
    if metrics:
        yaml_lines.append("model-index:")
        yaml_lines.append("- name: molfun-model")
        yaml_lines.append("  results:")
        yaml_lines.append("  - metrics:")
        for k, v in metrics.items():
            yaml_lines.append(f"    - name: {k}")
            yaml_lines.append(f"      type: {k}")
            yaml_lines.append(f"      value: {v}")
    yaml_lines.append("---")

    sections = ["\n".join(yaml_lines), ""]
    sections.append("# Molfun Model")
    sections.append("")

    if objective:
        sections.append(f"> {objective}")
        sections.append("")

    sections.append("This model was trained with [Molfun](https://github.com/rubencr14/molfun), "
                     "a modular framework for fine-tuning molecular ML models.")
    sections.append("")

    # Architecture
    sections.append("## Architecture")
    sections.append("")
    sections.append(f"- **Backend**: {model_summary.get('name', 'unknown')}")
    sections.append(f"- **Device**: {model_summary.get('device', 'unknown')}")

    adapter = model_summary.get("adapter", {})
    if adapter:
        sections.append(f"- **Total parameters**: {adapter.get('total', '?'):,}")
        sections.append(f"- **Trainable parameters**: {adapter.get('trainable', '?'):,}")

    head = model_summary.get("head", {})
    if head:
        sections.append(f"- **Head**: {head.get('type', '?')} ({head.get('params', '?'):,} params)")

    if isinstance(strategy, dict) and strategy:
        sections.append(f"- **Strategy**: {strategy.get('name', '?')}")

    peft = model_summary.get("peft", {})
    if peft:
        sections.append(f"- **PEFT**: rank={peft.get('rank', '?')}, "
                         f"alpha={peft.get('alpha', '?')}")

    sections.append("")

    # Metrics
    if metrics:
        sections.append("## Evaluation Results")
        sections.append("")
        sections.append("| Metric | Value |")
        sections.append("|--------|-------|")
        for k, v in metrics.items():
            sections.append(f"| {k} | {v:.6f} |" if isinstance(v, float) else f"| {k} | {v} |")
        sections.append("")

    # Usage
    sections.append("## Usage")
    sections.append("")
    sections.append("```python")
    sections.append("from molfun.models.structure import MolfunStructureModel")
    sections.append("")
    sections.append("model = MolfunStructureModel.from_hub(\"<REPO_ID>\")")
    sections.append("output = model.predict(batch)")
    sections.append("```")
    sections.append("")

    # Training
    if dataset_name:
        sections.append("## Training")
        sections.append("")
        sections.append(f"Trained on **{dataset_name}**.")
        sections.append("")

    sections.append(f"*Generated by Molfun on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    return "\n".join(sections)
